language: python
python:
- 3.6
- 3.7
- 3.8
install:
- pip install -r requirements.txt
- python setup.py install
deploy:
  provider: pypi
  user: __token__
  password:
    secure: H9owS+iDW4el4dglpWZSGq1BAqz4W4lw12jCphq675LnCJJxJsUvydwC7LXwAgknVGb7Bwg8h+qnmTTWOnYRo0FCimSfxhanG037tdh2q0tbStKuc0i1xC/92tsteydsJ8WK99iXTUDzOTy15xBn8tvIHFk3dfdBsZi7afM8IjQlRJr1XhUYT4RXYwoxVkGeEubVOxBBsttNRFh7XxVGw7M5uGynyXeFiNFzDCgc5E08dft1hT9t/O90QJNMlZuGgwvPgc9Bno1cSaJMjZc8hj1JysTFBQNCxpsyk4K70jVnk0XjQLLdiPTFSezjIa/qB0NJmAtDEANkFmZeK8eNhMTeLcTthfLiF5jNk3HPB082htWUXwd+AxCVtJH0LYlP9gp4I8rF0k4RgPz4iIDivvDlUwuQsk8nLO4qUCu+DIUpZNKd3w8l/9ACYnkNSpb77sLHiXNx8wln/BNcjVWqyk3E5KnyapQIPEpV2IyFuCdROMCkZUNkSbRpasnwyYMArAfdIsoKzyo1+M3MS/eTN8g0slz0sls38dQvAs3UwE/PczYRE5RDYkhro7zxB5MmUYRXj4ykebyqIxAsK/maH1ttS35CDxYnpAf2Ny67NmeggFsOHjqK3B02ZqB8o+oxO5cIMRCKtie43+/zOB7xVLWpyNy5Sp79cedPLXVTZ3w=
  distributions: sdist bdist_wheel
  skip_existing: true
script:
- echo "Done"
